const tools = [
    { id: 1, name: "Дриль Bosch", category: "Електроінструменти", price: 2500, image: "../assets/images/1.jpg", description: "Потужний дриль для свердління." },
    { id: 2, name: "Молоток Stanley", category: "Ручний інструмент", price: 400, image: "../assets/images/2.jpg", description: "Зручний молоток для ремонтних робіт." },
    { id: 3, name: "Циркулярна пила Makita", category: "Електроінструменти", price: 4500, image: "../assets/images/3.jpg", description: "Професійна пила для розпилювання дерева." },
    { id: 4, name: "Набір викруток Kraft", category: "Ручний інструмент", price: 600, image: "../assets/images/4.jpg", description: "10 штук у наборі з різними насадками." },
    { id: 5, name: "Шуруповерт DeWalt", category: "Електроінструменти", price: 3100, image: "../assets/images/5.jpg", description: "Акумуляторний шуруповерт із LED-підсвіткою." },
    { id: 6, name: "Рівень Stabila", category: "Вимірювальні інструменти", price: 1100, image: "../assets/images/6.jpg", description: "Будівельний рівень 60 см з високою точністю." },
    { id: 7, name: "Ножівка Bahco", category: "Ручний інструмент", price: 950, image: "../assets/images/7.jpg", description: "Ножівка для роботи по дереву." },
    { id: 8, name: "Перфоратор Makita", category: "Електроінструменти", price: 5200, image: "../assets/images/8.jpg", description: "Потужний перфоратор для бетону." },
    { id: 9, name: "Гайковий ключ Wera", category: "Ручний інструмент", price: 700, image: "../assets/images/9.jpg", description: "Регульований ключ для ремонту авто." },
    { id: 10, name: "Лобзик Bosch", category: "Електроінструменти", price: 3700, image: "../assets/images/10.jpg", description: "Електролобзик для точного розпилювання." },
    { id: 11, name: "Паяльник Yihua", category: "Паяльне обладнання", price: 1200, image: "../assets/images/11.jpg", description: "Цифровий паяльник з регулюванням температури." },
    { id: 12, name: "Викрутка з тріскачкою", category: "Ручний інструмент", price: 280, image: "../assets/images/12.jpg", description: "Компактна викрутка з реверсом." },
    { id: 13, name: "Набір свердел Bosch", category: "Аксесуари", price: 860, image: "../assets/images/13.jpg", description: "Набір свердел для металу, дерева та бетону." },
    { id: 14, name: "Шліфмашина Einhell", category: "Електроінструменти", price: 2900, image: "../assets/images/14.jpg", description: "Шліфмашина з пилозбірником." },
    { id: 15, name: "Лазерний рівень Huepar", category: "Вимірювальні інструменти", price: 2200, image: "../assets/images/15.jpg", description: "Лазерний рівень з зеленим променем." },
    { id: 16, name: "Плоскогубці Vorel", category: "Ручний інструмент", price: 310, image: "../assets/images/16.jpg", description: "Міцні плоскогубці для електромонтажу." },
    { id: 17, name: "Драбина алюмінієва", category: "Будівельне обладнання", price: 3300, image: "../assets/images/17.jpg", description: "4-секційна розкладна драбина." },
    { id: 18, name: "Клейовий пістолет Deko", category: "Паяльне обладнання", price: 520, image: "../assets/images/18.jpg", description: "Пістолет для термоклею з насадками." },
    { id: 19, name: "Набір торцевих головок", category: "Аксесуари", price: 1500, image: "../assets/images/19.jpg", description: "Комплект головок у кейсі на 36 предметів." },
    { id: 20, name: "Ножиці по металу", category: "Ручний інструмент", price: 470, image: "../assets/images/20.jpg", description: "Прямі ножиці для листового металу." },
    { id: 21, name: "Кутова шліфмашина", category: "Електроінструменти", price: 3100, image: "../assets/images/21.jpg", description: "Болгарка для різання металу." },
    { id: 22, name: "Набір ключів Intertool", category: "Ручний інструмент", price: 1100, image: "../assets/images/22.jpg", description: "12 ключів з хром-ванадієвої сталі." },
    { id: 23, name: "Мультиметр DT9205", category: "Вимірювальні інструменти", price: 780, image: "../assets/images/23.jpg", description: "Універсальний мультиметр для діагностики." },
    { id: 24, name: "Будівельна рулетка 5м", category: "Вимірювальні інструменти", price: 180, image: "../assets/images/24.jpg", description: "Механічна рулетка з фіксатором." },
    { id: 25, name: "Газовий паяльник Portasol", category: "Паяльне обладнання", price: 1650, image: "../assets/images/25.jpg", description: "Портативний паяльник без дротів." },
    { id: 26, name: "Електричний рубанок Makita", category: "Електроінструменти", price: 3800, image: "../assets/images/26.jpg", description: "Професійний інструмент для стругання деревини." },
    { id: 27, name: "Рулетка Stanley FatMax 8м", category: "Вимірювальні інструменти", price: 350, image: "../assets/images/27.jpg", description: "Міцна будівельна рулетка з магнітним наконечником." },
    { id: 28, name: "Набір шестигранників Matrix", category: "Аксесуари", price: 240, image: "../assets/images/28.jpg", description: "9 L-подібних шестигранників у кейсі." }
];

export default tools;
